name: Build and release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: actions/cache@v1
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install build dependencies
        run: pip install poetry
      - name: Install project requirements
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction
      - name: Build python and binary
        run: |
          poetry build
          poetry run pyinstaller sway-xkb-switcher.spec
          upx dist/sway-xkb-switcher
      - name: Calculate binary hash
        run: |
          cd dist
          sha256sum sway-xkb-switcher > sha256sum.txt
      - name: Publish to pypi
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
      - name: Create Github release
        uses: meeDamian/github-release@1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./dist/sway-xkb-switcher
            ./dist/sha256sum.txt
          gzip: false
